In [2]:
import numpy as np
import pandas as pd

import warnings
warnings.simplefilter("ignore")

In [3]:
df = pd.read_csv("mushrooms.csv")
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
X = df.drop("class", axis = 1)
y = df["class"]

# Train Test Split

In [5]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, mean_absolute_error

***Finding Best Random State***

In [14]:
list_to_encode = X.iloc[:,0:].columns.to_list()

In [18]:
train = []
test = []
cv = []

for i in range(100):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = i)

    step = ColumnTransformer(transformers = [
        ("col_tnf", OneHotEncoder(sparse = False, drop = "first"), list_to_encode )
    ], remainder = "passthrough")

    pipe = Pipeline([
        ("step", step),
        ("model", LogisticRegression())
    ])

    pipe.fit(X_train, y_train)
    pred_train = pipe.predict(X_train)
    pred_test = pipe.predict(X_test)

    train_accuracy = pipe.score(X_train, y_train)
    test_accuracy = pipe.score(X_test, y_test)
    cv_score = cross_val_score(pipe, X_train, y_train, cv = 5).mean()

    train.append(train_accuracy)
    test.append(test_accuracy)
    cv.append(cv_score)

ff = pd.DataFrame({
    "Train Model": train,
    "Test Model": test,
    "CV": cv,
})

In [20]:
ff

    Train Model  Test Model        CV
0      1.000000    1.000000  0.999692
1      0.999538    0.996923       NaN
2      0.999846    0.998769  0.999385
3      0.999846    0.999385  0.999384
4      1.000000    1.000000  0.999692
..          ...         ...       ...
95     0.999846    0.999385  0.999692
96     1.000000    1.000000  0.999385
97     1.000000    1.000000  0.999231
98     1.000000    0.999385  0.999692
99     1.000000    1.000000  0.999692

[100 rows x 3 columns]